version: '3'

services:
  app:
    tty: true
    stdin_open: true
    image: node:12.18.3
    ports:
      - 10000:3000
      - 9229:9229 # Debuging nodejs
    volumes:
    - ./app/:/app
    environment:
      - REDIS_URL=redis://cache
    working_dir: /app
    entrypoint: bash -c "npm install && npm run start.dev"
    links:
      - "neo4j:database"
      - "redis:cache"

  redis:
    image: redis
    expose:
      - 6379

  neo4j:
    image: neo4j:3.5
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test

      # - NEO4J_dbms_memory_pagecache_size=1G
      # - NEO4J_dbms.memory.heap.initial_size=1G
      # - NEO4J_dbms_memory_heap_max__size=1G
