version: '3'
services:
  web:
    build: ./backend
    ports:
      - 10000:80
  neo4j:
    image: neo4j:3.5
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test

      # - NEO4J_dbms_memory_pagecache_size=1G
      # - NEO4J_dbms.memory.heap.initial_size=1G
      # - NEO4J_dbms_memory_heap_max__size=1G
